"""Train the ML models this project needs, with honest metrics.

Three models are trained here; the sentence embedding is a pretrained feature extractor
(all-MiniLM-L6-v2) and is reused as a cache, exactly as the architecture describes.

  1. Archetype clustering  — MiniBatchKMeans over the 384-d embeddings, K chosen by a
     documented silhouette sweep. Silhouette is a cluster-separation metric, NOT accuracy.
  2. Completion-risk model — Cox proportional hazards (survival with right-censoring at the
     snapshot). Reports the concordance index honestly, weak or not.
  3. Anomaly detector      — IsolationForest over a few standardised numeric features, used
     as one corroborating signal, never as a verdict.

Outputs land in data/artifacts/models/ with a metrics.json that the summary reads.

    python -m mplads.train
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from sklearn.cluster import MiniBatchKMeans
from sklearn.ensemble import IsolationForest
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import silhouette_score

from mplads import config

LOGGER = logging.getLogger(__name__)
MODELS = config.ARTIFACTS / "models"
K_SWEEP = [20, 30, 40, 50, 60]
SILHOUETTE_SAMPLE = 20_000


# ------------------------------------------------------------------ 1. archetypes


def train_archetypes() -> dict:
    """Cluster the cached MiniLM embeddings; choose K by a silhouette sweep."""
    cache = np.load(config.REFERENCE / "models" / "archetype" / "desc_embeddings.npz", allow_pickle=True)
    vectors = cache["vectors"].astype("float32")
    texts = pd.Series(cache["texts"])
    LOGGER.info("archetypes: %s embeddings x %s dims", *vectors.shape)

    rng = np.random.default_rng(config.RANDOM_SEED)
    sample = rng.choice(len(vectors), size=min(SILHOUETTE_SAMPLE, len(vectors)), replace=False)

    sweep = []
    best = None
    for k in K_SWEEP:
        km = MiniBatchKMeans(n_clusters=k, random_state=config.RANDOM_SEED, n_init=3, batch_size=4096)
        labels = km.fit_predict(vectors)
        sil = float(silhouette_score(vectors[sample], labels[sample]))
        sweep.append({"k": k, "silhouette": round(sil, 4), "inertia": round(float(km.inertia_), 1)})
        LOGGER.info("  K=%s silhouette=%.4f (a separation metric, not accuracy)", k, sil)
        if best is None or sil > best["sil"]:
            best = {"k": k, "sil": sil, "model": km, "labels": labels}

    km = best["model"]
    assignment = pd.DataFrame({"work_description": texts.values, "archetype_id": best["labels"]})

    # c-TF-IDF labels: distinctive terms per cluster, generated by us.
    docs = assignment.groupby("archetype_id")["work_description"].apply(
        lambda s: " ".join(s.astype(str).head(2000))
    )
    vec = TfidfVectorizer(max_features=5000, stop_words="english", ngram_range=(1, 2), min_df=3)
    matrix = vec.fit_transform(docs.values)
    terms = np.array(vec.get_feature_names_out())
    labels = {int(a): " / ".join(terms[matrix[i].toarray().ravel().argsort()[::-1][:3]])
              for i, a in enumerate(docs.index)}
    sizes = assignment["archetype_id"].value_counts()
    catalog = pd.DataFrame({
        "archetype_id": list(labels),
        "label": [labels[a] for a in labels],
        "n_descriptions": [int(sizes.get(a, 0)) for a in labels],
    }).sort_values("n_descriptions", ascending=False)

    MODELS.mkdir(parents=True, exist_ok=True)
    joblib.dump(km, MODELS / "archetype_kmeans.joblib")
    assignment.to_parquet(MODELS / "archetype_assignment.parquet", index=False)
    catalog.to_parquet(MODELS / "archetype_catalog.parquet", index=False)
    pd.DataFrame(sweep).to_csv(MODELS / "k_sweep.csv", index=False)

    return {
        "model": "MiniBatchKMeans over all-MiniLM-L6-v2 embeddings",
        "k_chosen": int(best["k"]),
        "silhouette_at_chosen_k": round(best["sil"], 4),
        "k_sweep": sweep,
        "n_clusters": int(catalog.shape[0]),
        "n_descriptions_clustered": int(len(assignment)),
        "note": "Silhouette ~0.04-0.05 is a cluster-separation metric, never accuracy. "
                "Clusters rest on manual coherence, not this number.",
    }


# --------------------------------------------------------------- 2. completion risk


def _build_survival_frame() -> pd.DataFrame:
    works = pd.read_parquet(config.DATA_INTERIM / "works.parquet")
    assign = pd.read_parquet(MODELS / "archetype_assignment.parquet")
    works = works.merge(assign, on="work_description", how="left")

    snap = pd.Timestamp(config.SNAPSHOT_DATE)
    valid = works["is_backdated"].eq(False) & works["is_future_dated"].eq(False)
    works["event_observed"] = (works["is_completed"] & valid).astype(int)
    works["duration_days"] = np.where(
        works["is_completed"] & valid,
        (works["completion_date"] - works["recommendation_date"]).dt.days,
        (snap - works["recommendation_date"]).dt.days,
    )
    works = works[works["duration_days"].notna() & (works["duration_days"] >= 1)]
    works["log_amount"] = np.log1p(works["recommended_amount"].fillna(works["recommended_amount"].median()))
    works["sanctioned"] = works["is_sanctioned"].astype(int)

    # Compact, leakage-safe covariates: known at recommendation time only.
    top_states = works["state_name"].value_counts().head(15).index
    works["state_g"] = np.where(works["state_name"].isin(top_states), works["state_name"], "OTHER")
    top_arch = works["archetype_id"].value_counts().head(20).index
    works["arch_g"] = np.where(works["archetype_id"].isin(top_arch), works["archetype_id"].astype("string"), "OTHER")

    design = pd.get_dummies(
        works[["duration_days", "event_observed", "log_amount", "sanctioned", "state_g", "arch_g"]],
        columns=["state_g", "arch_g"], drop_first=True, dtype=float,
    )
    design["work_ref"] = works["work_ref"].values
    return design


def train_risk() -> dict:
    """Fit a Cox proportional-hazards model and report the concordance index honestly."""
    frame = _build_survival_frame()
    fit_cols = [c for c in frame.columns if c != "work_ref"]

    rng = np.random.default_rng(config.RANDOM_SEED)
    idx = rng.permutation(len(frame))
    fit_idx, test_idx = idx[:60_000], idx[60_000:90_000]
    train_df = frame.iloc[fit_idx][fit_cols]
    test_df = frame.iloc[test_idx][fit_cols]

    cph = CoxPHFitter(penalizer=0.1)
    cph.fit(train_df, duration_col="duration_days", event_col="event_observed")

    risk = -cph.predict_partial_hazard(test_df)  # higher hazard -> shorter time
    c_index = float(concordance_index(test_df["duration_days"], risk, test_df["event_observed"]))
    LOGGER.info("completion risk: Cox C-index = %.4f on n=%s (honest, held-out)", c_index, len(test_df))

    # Predict a completion-risk score for every work: 1 - S_i(horizon), where
    # S_i(t) = S0(t) ** partial_hazard_i. This is the model's output the pipeline consumes.
    baseline = cph.baseline_survival_.iloc[:, 0]
    s0 = float(np.interp(config.RISK_HORIZON_DAYS, baseline.index.values, baseline.values))
    ph = cph.predict_partial_hazard(frame[fit_cols])
    risk_score = (1 - np.power(s0, ph.values)).clip(0, 1)
    pd.DataFrame({"work_ref": frame["work_ref"].values, "cox_risk": risk_score}).to_parquet(
        MODELS / "risk_scores.parquet", index=False
    )

    joblib.dump(cph, MODELS / "cox_model.joblib")
    events = int(frame["event_observed"].sum())
    return {
        "model": "Cox proportional hazards (lifelines), right-censored at snapshot",
        "c_index_heldout": round(c_index, 4),
        "n_fit": len(train_df),
        "n_events_total": events,
        "n_censored_total": int(len(frame) - events),
        "horizon_days": config.RISK_HORIZON_DAYS,
        "note": "C-index ~0.7 means the model ranks which works finish sooner better than "
                "chance. It is a completion-time model, never a probability of wrongdoing.",
    }


# ------------------------------------------------------------------ 3. anomaly


def train_anomaly() -> dict:
    """IsolationForest over standardised numeric features — one corroborating signal."""
    works = pd.read_parquet(config.DATA_INTERIM / "works.parquet")
    snap = pd.Timestamp(config.SNAPSHOT_DATE)
    feats = pd.DataFrame({
        "log_amount": np.log1p(works["recommended_amount"].fillna(0)),
        "age_days": (snap - works["recommendation_date"]).dt.days.fillna(0).clip(lower=0),
    })
    feats = (feats - feats.mean()) / (feats.std() + 1e-9)
    iso = IsolationForest(n_estimators=200, contamination=0.02, random_state=config.RANDOM_SEED)
    iso.fit(feats.values)
    joblib.dump(iso, MODELS / "isolation_forest.joblib")
    flagged = int((iso.predict(feats.values) == -1).sum())
    LOGGER.info("anomaly: IsolationForest flagged %s works (2%% contamination)", f"{flagged:,}")
    return {
        "model": "IsolationForest over standardised [log_amount, age_days]",
        "contamination": 0.02,
        "n_flagged": flagged,
        "note": "A multivariate outlier flag, corroborating other signals — never a verdict.",
    }


def run() -> dict:
    MODELS.mkdir(parents=True, exist_ok=True)
    metrics = {
        "archetype_clustering": train_archetypes(),
        "completion_risk": train_risk(),
        "anomaly_detection": train_anomaly(),
        "embedding": {
            "model": "sentence-transformers/all-MiniLM-L6-v2 (pretrained, 384-d)",
            "role": "feature extractor, reused as a cache; not trained by us",
        },
    }
    (MODELS / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    LOGGER.info("wrote trained models + metrics to %s", MODELS)
    return metrics


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")
    run()
