"""The English source of every user-facing interface string.

One flat dictionary, translated as a unit and cached per language. Keys are stable; only
values are ever translated. Numbers and case-file content are translated separately at
request time because they change with the data.
"""

from __future__ import annotations

UI: dict[str, str] = {
    # navigation
    "nav.monitor": "Monitor",
    "nav.intelligence": "Intelligence",
    "nav.trust": "Trust",
    "nav.overview": "Overview",
    "nav.worklist": "Investigation Queue",
    "nav.trends": "Temporal",
    "nav.duplicates": "Near-Duplicates",
    "nav.compliance": "Compliance",
    "nav.archetypes": "Work Archetypes",
    "nav.transparency": "Data Transparency",
    "nav.how": "How it works",
    # shell
    "shell.brandSub": "Forensic Monitoring",
    "shell.stakeholder": "Stakeholder view",
    "shell.roleSim": "Role simulation — no authentication in this prototype",
    "shell.viewingAs": "Viewing as",
    "shell.chain": "Learn, Compare, Predict, Explain, Prioritise",
    "shell.leadsNotVerdicts":
        "Investigation leads, not fraud verdicts. A human decides every action.",
    # overview
    "overview.title": "National Overview",
    "overview.worksMonitored": "Works monitored",
    "overview.totalRecommended": "Total recommended",
    "overview.exposure": "Exposure at risk",
    "overview.exposureFoot": "Completion-risk weighted, not loss, not spend",
    "overview.leads": "Investigation leads",
    "overview.byState": "Exposure by state (top 10, crore)",
    "overview.bands": "Confidence bands",
    "overview.archetypes": "Learned work archetypes",
    "overview.completed": "completed",
    "overview.open": "open",
    # worklist
    "worklist.title": "Investigation Queue",
    "worklist.sub": "Ranked by Audit-ROI = priority x exposure x corroboration",
    "worklist.search": "Search description or implementing agency",
    "worklist.allStates": "All states",
    "worklist.allBands": "All bands",
    "worklist.empty": "No leads match these filters.",
    "worklist.work": "Work",
    "worklist.state": "State",
    "worklist.confidence": "Confidence",
    "worklist.amount": "Amount",
    "worklist.auditRoi": "Audit-ROI",
    "worklist.prev": "Previous",
    "worklist.next": "Next",
    "worklist.page": "Page",
    "worklist.of": "of",
    # case file
    "case.title": "Case File",
    "case.back": "Back to queue",
    "case.evidence": "Evidence — why this was surfaced",
    "case.peerContext": "Peer context",
    "case.nextStep": "Recommended next step",
    "case.recommended": "Recommended",
    "case.completionRisk": "Completion risk",
    "case.corroboration": "Corroboration",
    "case.families": "families",
    "case.earlyWarning": "Early warning",
    "case.compliance": "Compliance findings",
    "case.duplicate": "Near-duplicate candidate",
    "case.aiBrief": "AI briefing",
    "case.archetype": "Work type",
    "case.peerLevel": "Peer level",
    "case.peerSize": "Peer group size",
    "case.amountPercentile": "Amount percentile",
    # shared banners
    "banner.hitl":
        "Investigation leads, not fraud verdicts. Every item is ranked by audit "
        "return-on-investment from transparent, corroborated signals. There are no fraud "
        "labels in this data — a human reviews the evidence and decides what happens.",
    "common.loading": "Loading intelligence",
    "common.works": "works",
    "common.leads": "leads",
    "common.language": "Language",
    "common.generating": "Writing briefing",
    "common.exposure": "exposure",
    "common.weight": "weight",
    "common.notFound": "Page not found",
    "common.notFoundBody": "There is nothing at this address.",
    "common.notFoundCta": "Go to the National Overview",
    # compliance & early warning
    "compliance.title": "Compliance & Early Warning",
    "compliance.sub": "Lifecycle deviation checks and stalling risk",
    "compliance.authorityLead": "Authority matters.",
    "compliance.healthIndex": "MPLADS Operational Health Index",
    "compliance.earlyLevels": "Early-warning levels (open works)",
    "compliance.checks": "Lifecycle compliance checks",
    "compliance.check": "Check",
    "compliance.authority": "Authority",
    "compliance.severity": "Severity",
    "compliance.meaning": "What it means",
    # near-duplicates
    "duplicates.title": "Near-Duplicate Detection",
    "duplicates.sub": "Semantic similarity over 384-dimensional description embeddings",
    "duplicates.concerningPairs": "concerning pairs",
    "duplicates.normalLead": "Repeated descriptions are normal in this scheme",
    "duplicates.normalBody":
        "— one MP recommending forty street lights writes the same sentence forty times. So "
        "we only treat a pair as concerning when it is near-identical, from the same "
        "implementing agency, for a near-identical amount. That is the shape a repeated "
        "claim would take. It is a question for a human, never proof.",
    "duplicates.candidatesFound": "Candidate pairs found",
    "duplicates.concerning": "Administratively concerning",
    "duplicates.identicalText": "Character-identical text",
    "duplicates.sameAgency": "Same implementing agency",
    "duplicates.acrossBlocks": "across state x work-type blocks",
    "duplicates.sameAgencyAmount": "same agency + near-identical amount",
    "duplicates.candidatePairs": "Candidate pairs",
    "duplicates.workA": "Work A",
    "duplicates.workB": "Work B",
    "duplicates.similarity": "Similarity",
    # temporal
    "trends.title": "Temporal Intelligence",
    "trends.sub": "How the scheme is changing over time",
    "trends.agenciesAnalysed": "agencies analysed",
    "trends.method": "Method:",
    "trends.volume": "National monthly work volume",
    "trends.median": "National median recommended amount (thousand)",
    "trends.radar": "Emerging Public Works Radar",
    "trends.workType": "Work type",
    "trends.status": "Status",
    "trends.recentWorks": "Recent works",
    "trends.shareChange": "Share change",
    "trends.agenciesChanged": "Agencies whose behaviour changed",
    "trends.agency": "Implementing agency",
    "trends.totalWorks": "Total works",
    "trends.whyFlagged": "Why flagged",
    # data transparency
    "transparency.title": "Data Transparency",
    "transparency.sub":
        "What we measure, what we derive, and what the public data does not contain",
    "transparency.fieldsUnavailable": "fields unavailable",
    "transparency.measured": "Measured directly",
    "transparency.measuredFoot": "straight from government records",
    "transparency.derived": "Model-derived",
    "transparency.derivedFoot": "computed, with stated confidence",
    "transparency.unavailable": "Unavailable",
    "transparency.unavailableFoot": "absent from public data — not faked",
    "transparency.metric": "Metric",
    "transparency.source": "Source",
    "transparency.confidenceCol": "Confidence",
    "transparency.note": "Note",
    "transparency.completeness": "Field completeness (measured)",
    "transparency.groundTruth": "Ground truth from the field",
    "transparency.readyFor": "Ready for restricted government data",
    "transparency.field": "Field",
    "transparency.type": "Type",
    "transparency.wouldUnlock": "What it would unlock",
    "transparency.verifications": "Verifications recorded",
    "transparency.concernsConfirmed": "Concerns confirmed on site",
    "transparency.stillNeeded": "Still needed to fit weights",
    "transparency.outcome": "Outcome",
    "transparency.meaning": "Meaning",
    # archetypes
    "archetypes.title": "Work Archetypes",
    "archetypes.sub": "Work types the system discovered on its own from the descriptions",
    "archetypes.named": "named",
    "archetypes.medianSize": "Median size",
    "archetypes.completedPct": "Completed",
    "archetypes.typicalDuration": "Typical duration",
    "archetypes.flagged": "Flagged",
    "archetypes.distinctiveTerms": "Distinctive terms in this cluster",
    "archetypes.viewFlagged": "View flagged works in the queue",
    "archetypes.notInterpretable": "not interpretable",
    # case file (additions)
    "case.plainSummary": "Plain summary:",
    "case.auditRoiRank": "Audit-ROI rank score",
    "case.exposureFoot": "amount x completion risk",
    "case.basis": "basis",
    "case.familiesFired": "independent signal families fired",
    "case.matchedWork": "Matched work",
    "case.classification": "Classification",
    "case.similarity": "Similarity",
    # assistant
    "chat.assistant": "Assistant",
    "chat.open": "Ask the assistant",
    "chat.tools": "data tools",
    "chat.live": "live",
    "chat.offline": "offline",
    "chat.connecting": "connecting…",
    "chat.introLead":
        "I answer only by looking things up in the computed results. I have no independent "
        "knowledge of this data and cannot do arithmetic, so I cannot invent a figure — and "
        "I show you which tool produced every answer.",
    "chat.forThisScreen": "About this screen",
    "chat.orAsk": "Or ask about",
    "chat.all": "All",
    "chat.lookedUp": "Looked up",
    "chat.working": "Looking it up…",
    "chat.placeholder": "Ask about a work, a state, or the numbers…",
    "chat.send": "Send",
    "chat.copy": "Copy",
    "chat.copied": "Copied",
    "chat.listen": "Listen",
    "chat.stop": "Stop",
    "chat.export": "Export transcript",
    "chat.clear": "Clear conversation",
    "chat.expand": "Expand",
    "chat.restore": "Restore",
    "chat.close": "Close",
    "chat.speak": "Ask by voice",
    "chat.stopListening": "Stop listening",
    "chat.noVoice": "This browser cannot listen. Chrome or Edge can.",
    "chat.voiceFailed": "I could not hear that. Try again, or type it.",
    "chat.copyFailed": "The browser blocked copying.",
    "chat.unreachable":
        "I could not reach the assistant service. Check that the API is running on port 8000.",
}
